### ISSUE TITLE
Filtering by name: new design plan

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#100]
Above the table of elements on iFL tab, there should be a filtering option for filtering by name: 

![filter_by_name](https://user-images.githubusercontent.com/16755484/78662813-64088780-78d1-11ea-9451-b54c6f36d8cb.jpg)

The input field of name filtering should start where the ruler starts in line. 

Old issue: #43

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
