### ISSUE TITLE
Check Enable logging, then Apply and Close: the field will be unchecked opening Preferences again

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#101]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select the sample project (https://github.com/Frenkymd/experiment-sample). 
1. Select Window/Preferences. 
1. Check Enable logging. 
1. Give sample data: 
* User ID: test
* Scenario ID: test
* Host: 160.114.36.244
* Port: 10006
1. Apply and Close button. 
1. Open Window/Preferences again. 

**Expected results**
* Enable will be checked. 

**Received results**
* Enable was unchecked. 

![enable_logging_unchecked](https://user-images.githubusercontent.com/16755484/79312291-fd9ded80-7efe-11ea-9ba0-09ae398fcb08.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.1

**Comment by brita-sed** [comment]
Retested on V2.3.1. Result: **Corrected**.
