### ISSUE TITLE
Clicking on the slider should put the handle wherever I click

### ISSUE THREAD

**Issue by SzatmariA** [sed-szeged/iFL4Eclipse#102]
**Description**
Users are used to being able to move the handle on a slider by clicking. Having said that, I think it would be nice if I could put the handle on the slider wherever I click.  

**Actual behaviour**
I can drag the handle. However, when I click, it makes tiny movements.
![eclipse-workspace-experiment-sam](https://user-images.githubusercontent.com/17518412/79317450-0219d480-7f06-11ea-84d1-38adf1c7202c.gif)

**Expectation**
I can put the handle wherever I click on the slider. I can only do that by dragging at the moment. 

![Slider-jQuery-UI-Google-Chrome-2](https://user-images.githubusercontent.com/17518412/79317616-2f668280-7f06-11ea-9f73-ea5037f6f6e9.gif)

**Comment by Dhorvath1294** [comment]
The slider is no longer being used.
