### ISSUE TITLE
Sometimes scores.csv doesn't load properly

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#103]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select the sample project (https://github.com/Frenkymd/experiment-sample). 
1. Click iFL button. 
1. Load sample scores.csv. 

**Expected results**
* Scores will load appropriately. 

**Received results**
* "The plug-in was unable to open the CSV file. Please check if the CSV file is computed or is not properly formatted".

![hiba_csv_betoltes](https://user-images.githubusercontent.com/16755484/79320249-d00a7180-7f09-11ea-84a1-8c068f097411.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.1
