### ISSUE TITLE
ExecutionException, NullPointerException and NumberFormatException when Generate ID for invalid parametres

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#104]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Window/Preferences. 
1. Set invalid values for every ID, Host and Port: <iframe width="560" height="315" src="https://www.youtube.com/embed/cSMGIo6LW3k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
1. Click Generate ID. 

**Expected results**
* No exceptions, user-fiendly error messages. 

**Received results**
[lots_of_exception.log](https://github.com/sed-szeged/iFL4Eclipse/files/4480734/lots_of_exception.log)

![problem_occured_preferences](https://user-images.githubusercontent.com/16755484/79329436-1b2b8100-7f18-11ea-90f8-ed32a1ba0cfe.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
