### ISSUE TITLE
java.lang.IllegalArgumentException when giving invalid iFL preference parametres

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#105]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Window/Preferences. 
1. Set invalid values for every ID, Host and Port: <iframe width="560" height="315" src="https://www.youtube.com/embed/cSMGIo6LW3k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
1. Click Apply and Close. 
 

**Expected results**
* No exceptions, user-fiendly error messages. 

**Received results**
* "An error has occurred. See error log for more details. Error notifying a preference change listener. Check the log for details."
![problem_occured_preferences](https://user-images.githubusercontent.com/16755484/79329746-a0af3100-7f18-11ea-9287-d68c94d3c033.JPG)

![error_occured_preferences](https://user-images.githubusercontent.com/16755484/79338235-3a7dda80-7f27-11ea-81fe-deb56273ac26.JPG)

* Log file: 
[problem_occured_preferences.log](https://github.com/sed-szeged/iFL4Eclipse/files/4480762/problem_occured_preferences.log)

[numberFormatException.log](https://github.com/sed-szeged/iFL4Eclipse/files/4481205/numberFormatException.log)

**Related issue:**
* #104 

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
