### ISSUE TITLE
The rounding should be 4 decimal in Context based feedback dialog

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#108]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Right click -> Context based feedback. 

**Expected results**
* The rounding should be 4 decimal as in the main table.

![kerekites_feedback](https://user-images.githubusercontent.com/16755484/79553052-32937700-809c-11ea-8ed8-85ad0453c6f3.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.3

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.4. Result: **Corrected**.
