### ISSUE TITLE
Set element to "not faulty", than it can be set to faulty

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#11]
**Precondition**
* C:\experiment\eclipse\eclipse.exe has launched.  

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load scores...* button. 
1. Open C:\experiment\eclipse\sampleFor_TestProject.csv.
1. Select an element. 
1. Right click, choose *This is not faulty*. 
1. Right click on this element again, choose *This is faulty (terminal choice)*. 

**Expected results**
* Because this element was set as "Not faulty", *This is faulty (terminal choice)* operations should be inactive. 

**Received results**
* An item with zero points (decided it's not faulty at all) can be set to faulty. 
![faulty_not_faulty](https://user-images.githubusercontent.com/16755484/54135870-ed256480-441a-11e9-8bc5-4cab16d6c393.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
A quick fix could be to rename the option using it is less or more suspicious.

**Comment by geryxyz** [comment]
I implemented a quick fix, but it certainly part of a deeper problem. We should discuss this.
![image](https://user-images.githubusercontent.com/2602591/54672263-fdfb6780-4af7-11e9-842e-bdf7241ea2f6.png)

**Comment by brita-sed** [comment]
Retested on ifl_V0.4
Result: 
* I can set a "no faulty" item to faulty - is it a problem? 
* There isn't a dot at the end of the sentece in case of second option 
![dot_is_missing](https://user-images.githubusercontent.com/16755484/55083397-c5353280-50a3-11e9-8b5a-a11692ec870a.jpg)
