### ISSUE TITLE
In Context based feedback dialog Set to 1 label should be Set to 1.0

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#110]
In the Context based feedback dialog window, the button label of **Set to 1** should be **Set to 1.0**.

![set_to_1](https://user-images.githubusercontent.com/16755484/79561191-32e63f00-80a9-11ea-9354-3ad0356eae9b.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.3

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.4. Result: **Corrected**.
