### ISSUE TITLE
Used Set to 0.0 and Set to 1 buttons stay active after active checkboxes are not checked

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#111]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Right click -> Context based feedback. 
1. Set context to 0.0.
1. Set other to 1. 
1. Set all columns to inactive (the active checkbox should not be checked). 

**Expected results**
* All related button turns inactive. 

**Received results**
* The buttons used to set values to 0.0 and 1 before are stayed active in look, but they cannot be clickable. 

![stay_active](https://user-images.githubusercontent.com/16755484/79562004-958c0a80-80aa-11ea-8e28-7163e9e455ef.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.3

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.4. Result: **Corrected**.
