### ISSUE TITLE
Unhandled event loop exception, java.lang.UnsupportedOperationException after make a 1.0 or 0.0 column to inactive

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#112]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select the sample project (https://github.com/Frenkymd/experiment-sample). 
1. Click iFL button. 
1. Load scores. 
1. Right click -> Context based feedback. 
1. Set a column to 1 (or 0.0).
1. Set this column to inactive (the active checkbox should not be checked). 

**Expected results**
* All related button turns inactive, and there's no exception in the process. 

**Received results**
 ```
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsupportedOperationException
```

Log file: 
[unhandled_event_loop_exception.log](https://github.com/sed-szeged/iFL4Eclipse/files/4492477/unhandled_event_loop_exception.log)

**Related issue**
* #111

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.3

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.4. Result: **Corrected**.
