### ISSUE TITLE
java.lang.UnsupportedOperationException when process " Selected items seems faulty (terminal choice)" to an undefined scored element

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#116]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Select an element. 
1. Right click -> Selected items seems faulty (terminal choice). 

**Expected results**
* While there is no scores loaded, the option is inactive. 

**Received results**
* Function was active: 
** Nothing happened. 
** java.lang.UnsupportedOperationException in log file. [selected_seems_faulty_undefined.log](https://github.com/sed-szeged/iFL4Eclipse/files/4540404/selected_seems_faulty_undefined.log)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.9
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7.117

**Comment by brita-sed** [comment]
Corrected, a popup window shows that the operation is unsupported.
