### ISSUE TITLE
Move filter UI to a new ViewPart

### ISSUE THREAD

**Issue by Dhorvath1294** [sed-szeged/iFL4Eclipse#117]
In order to make the filter UI and the code element display UI more customized, the two should be put on separate ViewParts.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7.117

**Comment by brita-sed** [comment]
Retested on version V2.3.7.117. Result: **well implemented**. 

One feature request: #118 

**Comments**: 
It was an interesting sight to put the filtering settings in a separate view, which is good in that most of the table is visible. However, it may be good to have a recommendation on how to place the window.

1. If I put it towards the table, I can see both panels at the same time, which is good, but there is an unreasonable amount of space on the right side of the filters.
![filter_ures_hely](https://user-images.githubusercontent.com/16755484/80727759-65128a80-8b06-11ea-8a29-4e036e410b76.jpg)


1. If I put the panel next to the table, I have to constantly switch between the two tabs, it’s pretty annoying.
![filter_change_tab](https://user-images.githubusercontent.com/16755484/80727783-6cd22f00-8b06-11ea-9770-aa5d070bc816.JPG)


1. It’s best to put it in the bottom right corner of the window, but I had time to figure out that this is the most convenient layout.
![filter_botton_right_corner](https://user-images.githubusercontent.com/16755484/80727833-7eb3d200-8b06-11ea-88b2-9c3be87b1fdd.jpg)
