### ISSUE TITLE
Sort by is unnecessary while sorting can proceed in the table

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#118]
At Show filters panel Sort by is unnecessary while sorting can proceed by clicking on the header of a column. And anyway, its display is not very beautiful.

![sort_by_unnecessary](https://user-images.githubusercontent.com/16755484/80725358-3fd04d00-8b03-11ea-8351-f93dbadc55aa.jpg)

**Comment by Dhorvath1294** [comment]
The table has been replaced with a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
