### ISSUE TITLE
The two sort options are out of sync

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#119]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Show filters. 
1. Sort by a column in the table. 
1. Sort by another column in the filter panel. 

**Expected results**
* Sort by option in the iFL Filters panel will be shown on the table. 

**Received results**
* Using Sort by in the iFL Filters panel won't be seen in the table, the table won't refresh. 

![sorting_not_in_syncron](https://user-images.githubusercontent.com/16755484/80730816-58903100-8b0a-11ea-8582-7b2bae3a84e3.jpg)

**Related issue:**
* #118

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7.117
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The table has been replaced by a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
