### ISSUE TITLE
Icon plans for "Open details" local menu

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#12]
A new option was introduced in the ifl_V0.1 (z:\exchange\geryxyz\ifl_V0.1\) at the local menu. 

Icon: ![open_details_16x16](https://user-images.githubusercontent.com/16755484/54303815-21885480-45c4-11e9-8fdf-d876f913a1ee.png)
![open_details_32x32](https://user-images.githubusercontent.com/16755484/54303816-21885480-45c4-11e9-93a6-7ca766082709.png)

Design plan: 
![open_details_local_menu](https://user-images.githubusercontent.com/16755484/54303911-572d3d80-45c4-11e9-88e2-6dcb799c7a00.jpg)

**Comment by geryxyz** [comment]
#4

**Comment by brita-sed** [comment]
Icons now in the local menu, corrected. Package: ifl_V0.3
