### ISSUE TITLE
Table should be wider in Context based feedback dialog window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#121]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Right click on an element -> Context based feedback

**Expected results**
* The layout of the Context based feedback window is transparent, easy to interpret, aesthetic. 

**Received results**
* Tables in the bottom should be wider, reach until the end of the diagram. 

![table_recommendation](https://user-images.githubusercontent.com/16755484/81168610-9d4b1a80-8f97-11ea-824d-cf65d759c943.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7.117
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
This layout problem is still alive. 

![context_based_feedback_layout](https://user-images.githubusercontent.com/16755484/91568884-ec053180-e945-11ea-9de4-a920c7a72d3a.JPG)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs

Made the tables wider.

**Comment by brita-sed** [comment]
Retested, **not corrected**. There is still a gap between the end of graph and the right side of the table. 

![still_a_gap](https://user-images.githubusercontent.com/16755484/92578577-5003f000-f28c-11ea-88de-8ffa9a8e5f16.jpg)

**Comment by brita-sed** [comment]
This bug has been corrected with https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.3. 

![layout_corrected](https://user-images.githubusercontent.com/16755484/95434831-06252d00-0952-11eb-8cb6-37789fe40de3.JPG)
