### ISSUE TITLE
Graphical plans for Context based feedback window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#122]
Older issue: #56 

There should be
- **Set to 0** and **Set to 1** icon
- **Active** icon or text
- Type icon (selected, context, other)

I omitted the more detailed percentage icons (33%, 50%, 60%), as this seems to be accurate in the text anyway, and it would be unnecessary to create 100 icons for all possible changes.

![custom_feedback_icons](https://user-images.githubusercontent.com/16755484/81178306-4d288400-8fa8-11ea-813a-9e3a47f998c3.jpg)

![custom_feedback_icons_2](https://user-images.githubusercontent.com/16755484/81178303-4d288400-8fa8-11ea-915f-946e3f6bd430.jpg)

![custom_feedback_icons_3](https://user-images.githubusercontent.com/16755484/81178299-4bf75700-8fa8-11ea-9a6a-ead899d89b0d.jpg)

**Comment by brita-sed** [comment]
Corrected plan v2: 

![custom_feedback_icons_2_v2](https://user-images.githubusercontent.com/16755484/81183789-e14a1980-8faf-11ea-910e-aee69e9d2e0c.jpg)

**Comment by brita-sed** [comment]
Iconset: [icons.zip](https://github.com/sed-szeged/iFL4Eclipse/files/4587415/icons.zip)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs

**Comment by brita-sed** [comment]
Retested, **corrected**. 

![graphical_corrected](https://user-images.githubusercontent.com/16755484/92574214-1c729700-f287-11ea-841d-24e0dee3b81e.JPG)
