### ISSUE TITLE
There are no icons before values in the new grid view

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#123]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 

**Expected results**
* Elements will appear in a grid view with the appropriate information. 

**Received results**
* There are no icons before values. 

![no_icons](https://user-images.githubusercontent.com/16755484/81194200-a5698100-8fbc-11ea-942a-cbd72b65cf5b.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.1
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3

**Comment by brita-sed** [comment]
Corrected in version V2.4.52.3. 

![icons_corrected](https://user-images.githubusercontent.com/16755484/81691427-172e4880-945d-11ea-9d0b-03302f3d61ae.JPG)
