### ISSUE TITLE
The frame of the grid view don't adjust to the size of the iFL window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#124]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Resize iFL window to a smaller size. 

**Expected results**
* The frame of the grid view will adjust to the size of the iFL window.

**Received results**
* As the frame of the grid view hasn't adjust to the size of the iFL window, the scroll bar could disappear and won't be usable. 

![grid_frame_no_resize](https://user-images.githubusercontent.com/16755484/81197922-2aef3000-8fc1-11ea-9005-93ba9477d4ed.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.1
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The grid view no longer uses a scrollable container; instead, a pager is used.
