### ISSUE TITLE
Local menu on element where interactivity is "User feedback enabled" and no loaded scores: the first point should be corrected

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#125]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Right click on an element where the interactivity is "User feedback enabled". 

**Expected results**
* One line of the local menu is "Undefined score" or something like this. 

**Received results**
* The local menu says that "User feedback is disabled". The menupoint should be corrected. 

![user_feedback_fail](https://user-images.githubusercontent.com/16755484/81421711-2dcd5a80-9152-11ea-8027-0dbbff1ea002.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3

**Comment by brita-sed** [comment]
Corrected in version V2.4.52.3. 

![undefined_corrected](https://user-images.githubusercontent.com/16755484/81692716-1b5b6580-945f-11ea-89e1-7a8d7855d886.jpg)
