### ISSUE TITLE
Unhandled event loop exception, org.eclipse.swt.SWTException: Widget is disposed error message when select Context based feedback in local menu more times

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#127]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Select a "User feedback enabled" element. 
1. Right click -> Context based feedback. 
1. Change values, then click OK. 
1. Repeat steps 4-5-6 two or three times. 

**Expected results**
* The dialog window of Context based feedback is always appears correctly when choosing this from local menu. 

**Received results**
* No dialog window appears after the second or third try. 
* Unhandled event loop exception, org.eclipse.swt.SWTException: Widget is disposed error message in log. 

[second_click_of_contextbased.log](https://github.com/sed-szeged/iFL4Eclipse/files/4600273/second_click_of_contextbased.log)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.2
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
The problem is the same when selecting elements: 
![selection_unhandled](https://user-images.githubusercontent.com/16755484/81543522-76655d80-9376-11ea-9ffd-14a9f2f7ad11.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3

**Comment by brita-sed** [comment]
Corrected in version: V2.4.52.3. No error in log created.
