### ISSUE TITLE
Recommendation for "Selected element" layout design

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#128]
When the user selects an element from the grid layout, the selection will appear in a blue color. But after navigating to another page, selection will disappear. So the user cannot select element from different pages. To solve this problem, it would be worthwhile to create a separate column for the already selected items that could be freely removed from the selection.

![design_selected_element_kisebb](https://user-images.githubusercontent.com/16755484/81809388-95ecb980-9521-11ea-9c15-f7da0ce0bfa9.jpg)
![design_selected_element_2](https://user-images.githubusercontent.com/16755484/81809390-97b67d00-9521-11ea-8dac-2b446c8d1659.jpg)
![design_selected_element_01](https://user-images.githubusercontent.com/16755484/81809393-99804080-9521-11ea-8ed6-b4920dd020bc.jpg)

Icons: 
![moveback_deselect_16x16](https://user-images.githubusercontent.com/16755484/81809532-db10eb80-9521-11ea-9b62-8eb53b2c80e6.png)
![delete_deselect_16x16](https://user-images.githubusercontent.com/16755484/81809537-dcdaaf00-9521-11ea-9eed-bb4d6bdd10a2.png)

**Comment by geryxyz** [comment]
I suggest to display the signiture instead, because the name will be the same for several items

**Comment by brita-sed** [comment]
The process of selecting an element would be: 

![design_selected_element_change](https://user-images.githubusercontent.com/16755484/81813556-e830d900-9527-11ea-8777-e908f839be12.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.4

**Comment by brita-sed** [comment]
Tested on V2.4.52.5. Result: **implemented**.
