### ISSUE TITLE
If the name of the element is long, the feedback icon will slip off from the grid

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#130]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Select an item. 
1. Right click -> Context based feedback. 
1. Set different values, then click OK. 

**Expected results**
* The icon of the operation will appear in the right top bottom of each grid. 

**Received results**
* If the name of the element is long, the icon will slip off from the grid. 

![icon_slip_off](https://user-images.githubusercontent.com/16755484/81819571-c4719100-952f-11ea-8743-61bebaa0b894.jpg)

![icon_slip_off_2](https://user-images.githubusercontent.com/16755484/81823895-208ae400-9535-11ea-83ec-efc0eb4b5f6f.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The icons have been changed and relocated.
