### ISSUE TITLE
The icon of feedback of context elements will slip off from their grid

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#131]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Select an item, which has a long name and has more context items. 
1. Right click -> Context based feedback. 
1. Set different values, then click OK. 

**Expected results**
* The icon of the operation will appear in the right top bottom of each grid. 

**Received results**
* If the user choose an element, which has a long name, then set different feedback for context, the icon of the context grids (no matter that their name is long or short) will slip off too. 

![context_slip_off](https://user-images.githubusercontent.com/16755484/81824394-b888cd80-9535-11ea-8aa7-ade2d4bf0285.jpg)

**Related issue:**
* #130

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The icons have been changed and relocated.
