### ISSUE TITLE
The top of the grid layout and the selected elements are not in the same position

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#133]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Add some element to Selected elements. 

**Expected results**
* The layout is user-friendly and transparent. 

**Received results**
* The top of the grid layout and the selected elements are not in the same position. 

![selected_margin](https://user-images.githubusercontent.com/16755484/82031420-277f3700-969a-11ea-8877-d947f28bdc00.jpg)

**Related issue:**
* #128

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.4
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.5

**Comment by brita-sed** [comment]
Retested on V2.4.52.5. Result: **corrected**.
