### ISSUE TITLE
Selected elements disappear when the user change "Show scores"

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#134]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... 
1. Add some elements to _Selected elements_. 
1. Set different value in _Show scores_ rule. 

**Expected results**
* List of selected elements won't change. 

**Received results**
* Selected elements disappeared. 
* Not only Show scores, but Show context size, Filter by name also makes selected elements disappear. 

![selected_element_disappear](https://user-images.githubusercontent.com/16755484/82033621-46cb9380-969d-11ea-8d90-cded6431aa49.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.4
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.6

**Comment by brita-sed** [comment]
Retested on version: V2.4.52.6. Result: **corrected**.
