### ISSUE TITLE
Reposition of the pager below the grid

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#135]
The Pager could be in the middle below the grid layout and closer to the grids, currently the margin is unnecessarily large, taking up a lot of space.

![grid_pager](https://user-images.githubusercontent.com/16755484/82037272-310c9d00-96a2-11ea-9346-732b222c4248.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
