### ISSUE TITLE
After removing the second element from selected elements, the history won't be displayed again

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#136]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Set context feedback for some element with different values. 
1. Add an element with history to Selected elements. 
1. Add another element to Selected elements. 
1. Remove the second one from Selected elements. 

**Expected results**
* After select two element, history should disappear -> done. After removing the second element from selected elements, the history should be displayed again for the one selected element. 

**Received results**
* After removing the second element from selected elements, the history won't be displayed again.

![history_select_1](https://user-images.githubusercontent.com/16755484/82043468-ee4fc280-96ab-11ea-85b0-314f58c921ef.jpg)
![history_select_2](https://user-images.githubusercontent.com/16755484/82043469-eee85900-96ab-11ea-97b3-f58ebe008cdc.jpg)
![history_select_3](https://user-images.githubusercontent.com/16755484/82043463-ed1e9580-96ab-11ea-9cb7-9503bd7f966d.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.4
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.5

**Comment by brita-sed** [comment]
Retested on V2.4.52.5. Result: **corrected**.
