### ISSUE TITLE
History has been stucked when there are no selected elements

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#137]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Set context feedback for some element with different values. 
1. Add an element with history to Selected elements. 
1. Remove this element from Selected elements. 

**Expected results**
* As there are no selected elements, history won't be displayed. 

**Received results**
* History has been stucked when there are no selected elements. 

![after_selection](https://user-images.githubusercontent.com/16755484/82045698-d24e2000-96af-11ea-85bf-e9ca376f01d4.jpg)

**Related issue:**
* #85

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.4
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.5

**Comment by brita-sed** [comment]
Retested on version V2.4.52.5. Result: **corrected**.
