### ISSUE TITLE
Sort by: Last action, then change feedback values -> sorting won't change

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#140]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Select some element. 
1. Right click -> Context based feedback. 
1. Change values, then click OK.
1. **Sort by**: Last action. 
1. Repeat steps 4-5-6. 

**Expected results**
* The sorting will change according to changed values. 

**Received results**
* The sorting haven't been changed. 

![change_sorting_no_change](https://user-images.githubusercontent.com/16755484/82342866-6c84cf80-99f2-11ea-8595-15adfb85544b.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.140.1

**Comment by brita-sed** [comment]
Retested on version V2.5.140.1. Result: **corrected**.
