### ISSUE TITLE
Card highlight feature

### ISSUE THREAD

**Issue by Dhorvath1294** [sed-szeged/iFL4Eclipse#141]
Having multiple elements selected on one page can make it difficult for the user to associate the individual selected element cards with the original code element cards. Therefore, a suggestion has been made to include the following feature: when hovering the mouse cursor over a selected element card, the corresponding code element card should get highlighted.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.141.1

**Comment by brita-sed** [comment]
The function has been successfully implemented.
