### ISSUE TITLE
Empty string can be given for text-based inputs at Filters window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#146]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Click Add rule at Interactive Fault Localization Filters window. 
1. Select Name/Signature/Parent type/Path.
1. Enter some space characters, or leave the field empty. 
1. Click Add button. 

**Expected results**
* Space characters cannot be given for string input. 
* Input cannot be left blank, if I want to add it as a rule. 

**Received results**
* The rule was saved and displayed at rules list. 

![empty_string](https://user-images.githubusercontent.com/16755484/83276490-f42bc480-a1d0-11ea-8c33-20ce761eda76.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.1
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.2

**Comment by brita-sed** [comment]
Retested on version V2.5.144.2. Result: **corrected**. 

![empty_string_corrected](https://user-images.githubusercontent.com/16755484/84258149-befb6c80-ab16-11ea-8c56-4e742b3c9139.JPG)
