### ISSUE TITLE
Deleting rule with space characters: Unhandled event loop exception, NullPointerException

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#147]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Click Add rule at Interactive Fault Localization Filters window. 
1. Select Name/Signature/Parent type/Path.
1. Enter some space characters, or leave the field empty. 
1. Click Add button. 
1. Press X button at the card of the rule. 

**Expected results**
* The rule will be deleted. 

**Received results**
* !MESSAGE Unhandled event loop exception
	!STACK 0
	java.lang.NullPointerException
* Video: z:\team\columbus\projects\kutatas\iFL\empty_string_x.avi
* Log file: [unhandled_event_loop_exception.log](https://github.com/sed-szeged/iFL4Eclipse/files/4702809/unhandled_event_loop_exception.log)

**Related issue:**
* #146 

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.1
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
The problem is the same where there are a lot of element selected, after deleting a sorting rule: 

![unhandled_delete_rule](https://user-images.githubusercontent.com/16755484/86232782-c1d90280-bb94-11ea-97ed-ed95e96ac401.JPG)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-filter-bugs

**Comment by brita-sed** [comment]
There wasn't any error message in log (filtering, deleting), and names leaving empty or with spaces cannot be given. 

![cannot_add_space_rule](https://user-images.githubusercontent.com/16755484/94944098-0b5d2480-04d9-11eb-90a5-80df30b041db.JPG)
