### ISSUE TITLE
Header icon is missing from Create rule dialog

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#149]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Click Add rule at Interactive Fault Localization Filters window. 

**Expected results**
* The dialog window appears correctly. 

**Received results**
* Header icon is missing. 

![no_header](https://user-images.githubusercontent.com/16755484/83528303-3dd62100-a4e9-11ea-8e3a-fc30b42b667f.jpg)

**Related issue:**
* #148

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.1
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.2

**Comment by brita-sed** [comment]
Retested on version V2.5.144.2. Result: **corrected**. 
![create_rule_header_corr](https://user-images.githubusercontent.com/16755484/84257856-501e1380-ab16-11ea-93a5-3d88c4aa725c.JPG)
