### ISSUE TITLE
Layout plans for Create rule dialog window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#150]
Here you can see the layout recommendations for each submenu for Create rule dialog. 

![create_rule_last_action](https://user-images.githubusercontent.com/16755484/83621273-be9b2880-a58e-11ea-979e-26972de53546.jpg)

![create_rule_path](https://user-images.githubusercontent.com/16755484/83621787-6ca6d280-a58f-11ea-8596-0223ff4333d1.jpg)

![create_rule_interactivity](https://user-images.githubusercontent.com/16755484/83630339-f3fa4300-a59b-11ea-8e7f-6d454309d937.jpg)

![create_rule_score_3](https://user-images.githubusercontent.com/16755484/84025137-55028c00-a98b-11ea-801e-93101e03cdbe.jpg)

![create_rule_position](https://user-images.githubusercontent.com/16755484/84026173-238ac000-a98d-11ea-8ad8-b85dcf4f94c1.jpg)

![create_context_size](https://user-images.githubusercontent.com/16755484/83638680-ce743600-a5a9-11ea-8c1c-4163ec9e7a35.jpg)

Icons: [rules.zip](https://github.com/sed-szeged/iFL4Eclipse/files/4723387/rules.zip)

**Comment by brita-sed** [comment]
New version for Name and Path rules: 

![create_rule_path_v2](https://user-images.githubusercontent.com/16755484/84018461-5ed2c200-a980-11ea-95f0-10e1cd0c4d30.jpg)

[rules_v2_name_path.zip](https://github.com/sed-szeged/iFL4Eclipse/files/4745258/rules_v2_name_path.zip)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.2

**Comment by brita-sed** [comment]
Retested on version V2.5.144.2. Result: **NOT corrected**. 

If the rule is "contains", icon should be the contains icon: 

![contains_icon](https://user-images.githubusercontent.com/16755484/84259217-6f1da500-ab18-11ea-9b87-42a14263a382.jpg)

Score has a new icon now: 

![rules_icon](https://user-images.githubusercontent.com/16755484/84259488-d76c8680-ab18-11ea-9ee1-c5bb9260cfc8.jpg)

Position has a new icon now: 

![positon_icon](https://user-images.githubusercontent.com/16755484/84259714-2f0af200-ab19-11ea-9d19-17f6cb6d7d76.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.3

**Comment by brita-sed** [comment]
Layout has been fixed. Retested on version **V2.5.144.3**.
