### ISSUE TITLE
New icons for Context size 

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#152]
Related issue: #52

![context_size_new_red](https://user-images.githubusercontent.com/16755484/83639772-73dbd980-a5ab-11ea-9858-42f9831c4899.png)
![context_size_new](https://user-images.githubusercontent.com/16755484/83639776-74747000-a5ab-11ea-8fe6-67e3e55a9bd6.png)

Context size icon should be changed, because new "Case-sensitive" attribute needs the old one.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.2

**Comment by brita-sed** [comment]
Retested on version V2.5.144.2. Result: **corrected**. 

![context_size_corrected](https://user-images.githubusercontent.com/16755484/84258260-e94d2a00-ab16-11ea-97bd-dd015359fb4b.JPG)
