### ISSUE TITLE
Interactivity = false rule: User feedback enabled element occured.

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#155]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. At iFL Filters window click Add rule button. 
1. Add the following rule: Interactivity = false. 

**Expected results**
* Only User feedback disabled element will be displayed. 

**Received results**
* User feedback enabled element occured. 

![user_feedback_not_interactive](https://user-images.githubusercontent.com/16755484/85122346-b0a00580-b226-11ea-9fb1-a224aa17b811.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-filter-bugs

**Comment by brita-sed** [comment]
The bug has been **corrected**. Both true/false is working for interactivity rules.
