### ISSUE TITLE
Problems with context size filtering

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#156]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. At iFL Filters window click Add rule button. 
1. Add different context size rules. 

**Expected results**
* Results are correct. 

**Received results**
* The results for the various given relations are not correct.

![missing_three](https://user-images.githubusercontent.com/16755484/85125629-412d1480-b22c-11ea-92a4-7483fb7c4004.jpg)
![context_size_smaller](https://user-images.githubusercontent.com/16755484/85125634-41c5ab00-b22c-11ea-9a31-70b75bc396d6.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5.144.3
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-filter-bugs

**Comment by brita-sed** [comment]
The bug has been **corrected**, filtering is working now retested with the two cases above.
