### ISSUE TITLE
Typing the name of the faulty element: uppercase and lowercase letters are different

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#16]
**Precondition**
* C:\experiment\eclipse\eclipse.exe has launched.  

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar.
1. Click Load scores on the iFL tab. 
1. Choose a valid CSV.
1. Right click on an item, the choose *This is faulty (terminal choice)* option. 

**Expected results**
* The appropriate information is displayed in the dialog box.

**Received results**
* Maybe the text should contain the uppercase and lowercase letters are different. 
![upper_lower_case_faulty](https://user-images.githubusercontent.com/16755484/54364645-99f72000-466d-11e9-9ebe-f3b5aa96414e.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
We have to state that it is case sensitive, even when this is common knowledge among Java developers.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.16.1

**Comment by brita-sed** [comment]
Retested on V1.5.16.1. Result: **Corrected**. 

![case_sensitive](https://user-images.githubusercontent.com/16755484/61367164-5d416c80-a88b-11e9-9b75-f0dbf59f17a3.jpg)
