### ISSUE TITLE
Selected items seems faulty: in case of more elements the plugin won't validate the correct names

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#161]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. Select one element. 
1. Right click: Selected items seems faulty (terminal choice) 
1. Type the name of the method. 
1. Repeat step 4-6 with more elements. 

**Expected results**
* No matter how many elements are selected, in case of correct name it will be green and accepted. 

**Received results**
* If there are more elements which are faulty, the plugin won't validate the correct names. 

![select_one_or_more_faulty](https://user-images.githubusercontent.com/16755484/89661967-acfa3800-d8d3-11ea-96d0-c2c7c8389dfd.jpg)

**Related issue:**
* #160 

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs.2

**Comment by brita-sed** [comment]
Retested on version given above, result: **corrected**.

![terminal_corrected](https://user-images.githubusercontent.com/16755484/91565793-0ab5f900-e943-11ea-9f82-8acdeb77d5c3.JPG)
