### ISSUE TITLE
After setting scores to 1, set scores to 0 requires three clicks

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#164]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores... button. 
1. Right click on a "User feedback enabled" element. 
1. Select "Context based feedback". 
1. Try to set scores to 0 and 1.

**Expected results**
* Clicking on 0 button: scores set to 0. 
* Clicking on 1 button: scores set to 1. 

**Received results**
* If I set scores to 1 first, then clicking on 0, scores won't set to 0. Video: 

https://drive.google.com/file/d/12_qnZUaKSPZCx9GiTGBAD8bx1u7lkIvI/view?usp=sharing

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.2

**Comment by brita-sed** [comment]
Retested, result: **corrected**.
