### ISSUE TITLE
Layout corrections for Context based feedback window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#165]
As the new layout (#122) had been implemented, there are some issues which should be corrected: 

The _selected_, _context_ and _other_ icon, and the _will change_ part should be in the middle above/below of the white box of dots. 

![layout_context_feedback](https://user-images.githubusercontent.com/16755484/92587893-8ba4b700-f298-11ea-8d8e-d376e9b83d00.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.2

**Comment by brita-sed** [comment]
The top layout is corrected, but sorry, I forgot to sign the icon layout at the bottom :( It should be corrected too. 

![layout_context_feedback_2](https://user-images.githubusercontent.com/16755484/94940896-6d675b00-04d4-11eb-9a82-b15e849b0d32.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.3

**Comment by brita-sed** [comment]
The layout has been corrected. 

![layout_corrected](https://user-images.githubusercontent.com/16755484/95433367-1f2cde80-0950-11eb-8e3e-cdef3b00f8e5.JPG)
