### ISSUE TITLE
Click on < at Dual list tab: UnsupportedOperationException

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#177]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores...
1. Choose some cards. 
1. Click Show ordering list button. 
1. Click on < button. 

**Expected results**
* Nothing happens (every attribute is on the left side). 

**Received results**
* !MESSAGE Unhandled event loop exception
!STACK 0
java.lang.UnsupportedOperationException: Valid item to move is not selected.

![unsupported_ex](https://user-images.githubusercontent.com/16755484/107039021-ab93c480-67bd-11eb-920f-0adef504609d.jpg)
[show_ordering_list_exception.txt](https://github.com/sed-szeged/iFL4Eclipse/files/5932637/show_ordering_list_exception.txt)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
The problem is the same when I try to click ordering down an up icons with no selection. 

![dual_no_selection](https://user-images.githubusercontent.com/16755484/107039323-0cbb9800-67be-11eb-9ab4-07720c06ae2a.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.1

**Comment by brita-sed** [comment]
No more exception has come, the bug has been corrected.
