### ISSUE TITLE
At iFL dual tab an attribute can be moved to the right panel more than once

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#178]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores...
1. Choose some cards. 
1. Click Show ordering list button. 
1. Select an element. 
1. Click on > button more than once. 

**Expected results**
* After the first click, the attribute will be moved to the right panel, then the selection disappers. 

**Received results**
* Although the selection disappears, an attribute can be moved a lot of times to the right panel. 

![lots_of_attribute](https://user-images.githubusercontent.com/16755484/107041786-33c79900-67c1-11eb-8bcb-1273b7c362d9.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
And can be order in opposite ways: 

![duble_list_opp](https://user-images.githubusercontent.com/16755484/107200695-51cb0e80-69f8-11eb-9cba-ad08978abe86.JPG)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.1

**Comment by brita-sed** [comment]
The bug has been corrected.
