### ISSUE TITLE
After choosing a faulty item, iFL Dual list tab won't close

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#179]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 
1. Load scores...
1. Right click on a card. 
1. Selected items seems faulty (terminal choice)
1. Type the name of the method. 
1. Click OK button. 

**Expected results**
* Every iFL tab closes. 

**Received results**
* Interactive Fault Localization Dual list tab won't close, buttons are clickalbe, but nothing happens.

![dual_wont_close](https://user-images.githubusercontent.com/16755484/107047299-f3b7e480-67c7-11eb-8579-35d4c380abb2.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.1

**Comment by brita-sed** [comment]
Every tab has been closed, so the bug has been fixed.
