### ISSUE TITLE
The main iFL tab should be active at start, not the iFL Dual List tab

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#180]
**Precondition**
* .../eclipse.exe has launched.  
* iFL plugin has been installed. 

**Steps**
1. Select a project.
1. Click iFL button. 

**Expected results**
* The main iFL tab will be active. 

**Received results**
* The iFL Dual List tab was active. It is very uncomfortable to nagivate back everytime to the main tab. 

![maintab_should_be_first](https://user-images.githubusercontent.com/16755484/107049392-53af8a80-67ca-11eb-97bf-04f309247ed8.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.duallist-sorting.1

**Comment by brita-sed** [comment]
At start the main iFL tab is the choosen one, bug has been corrected.
