### ISSUE TITLE
Layout of the coloring and selection of an item

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#19]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Load scores from C:\experiment\eclipse\sampleFor_TestProject.csv
1. Find an item which has more context (parent type). 

**Expected results**
* Red coloring of the line is regular, from line to end of line. 

**Received results**
* Selection keeps line to line, but the red coloring start after a few mm from the grey rectangle. 
![coloring_layout](https://user-images.githubusercontent.com/16755484/54375858-1dbb0780-4682-11e9-9256-3ba7dcb1fbd3.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
The table has been replaced with a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
