### ISSUE TITLE
Sorting table - Design recommendation

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#2]
After loading the iFL plugin, the appearing table can be sortable. Currently, sorting is only visible after sorting. It would be recommended that the chance of sorting would be visible all the time with small triangles. The current order would be signed with a darker gray triangle.

![sorting](https://user-images.githubusercontent.com/16755484/53965525-afaa9980-40f1-11e9-9bb3-c966a8792857.jpg)

**Comment by geryxyz** [comment]
I have already begun to migrate from SWT Table to JFace TableViewer because of some other reasons. #5 Since it will support much more customization than the current one, we have to revisit this issue after the migration finished.

**Comment by Dhorvath1294** [comment]
A complete rework of the UI has taken place.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
