### ISSUE TITLE
Path, Lineinfo and Context size columns cannot be arranged

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#21]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Try to arrange all of the columns. 

**Expected results**
* Every column can be arranged. 

**Received results**
* Path, Lineinfo and Context size columns cannot be arranged, they cannot be moved forward, backward. 
* After loading scores Path can be arranged two times, but the third time it gets fixed. 

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.21.1

**Comment by brita-sed** [comment]
Retested on V1.5.21.1. Result: **Corrected.**
