### ISSUE TITLE
Recommendation for giving values manually for filter scores (design)

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#22]
For most software, where users can give values, they can manually enter them in addition to other value-giving ways. In this case, a manual input field would also be useful for the *filter score* function in addition to give the required values with slider. Design Plan:

![filter_score_manual](https://user-images.githubusercontent.com/16755484/54746830-7aac4580-4bcd-11e9-94d1-56a38737c942.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.44.1

**Comment by brita-sed** [comment]
Manually value giving is now working, tested on version 1.2.44.1.
