### ISSUE TITLE
Recommendation for "user feedback disabled" column

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#23]
In the current version of iFL for items where user feedback is not possible "(user feedback enabled)" text appears in red color, while where it is possible the cell is empty. Impression would be nicer if all the cells were filled, and the brackets also seems unnecessary. Maybe the text could start with uppercase like "User feedback disabled". 

Design Plan:

![user_feedback_enabled](https://user-images.githubusercontent.com/16755484/54748401-d8429100-4bd1-11e9-8d71-14db423488b7.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.44.1

**Comment by brita-sed** [comment]
The bug was corrected (retested on version 1.2.44.1): 

![user_feedback_disabled_corrected](https://user-images.githubusercontent.com/16755484/60182431-99515680-9824-11e9-9705-f0be65eeabdd.JPG)
