### ISSUE TITLE
Default setting of score filter value

### ISSUE THREAD

**Issue by abeszedes** [sed-szeged/iFL4Eclipse#24]
The score filter slider should be preset to a value which will result in a small amount of elements to display on startup. For example:
1, setting to fix 0.9
2, setting to the 90% of the maximum value
3, setting to the 90% of the max-min interval
4, setting to a value which results in N (=50) elements

**Comment by geryxyz** [comment]
#26

**Comment by brita-sed** [comment]
Retested on ifl_V0.4
Result: corrected: the filtering starts from a higher value. 

![base_after_load](https://user-images.githubusercontent.com/16755484/55174336-8bd0f580-517d-11e9-9cc5-9d6a57a2dfa3.JPG)
