### ISSUE TITLE
Filter by count of source code items in the context

### ISSUE THREAD

**Issue by geryxyz** [sed-szeged/iFL4Eclipse#26]

**Comment by Dhorvath1294** [comment]
Extra specification: this display filter has extra options depending on wether the user wishes to display items which posses a greater, lesser or equal amount of context size compared to the filter value.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.44.1

**Comment by brita-sed** [comment]
The feature works, retested on version 1.2.44.1
