### ISSUE TITLE
"Navigate to context" feature request 

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#29]
In the local menu of an element, there is a *Navigate to context* point. Currently it is not working, only the place of it fixed. 

![navigate_to_context](https://user-images.githubusercontent.com/16755484/54826748-c126a080-4cb0-11e9-88e0-dc995376feed.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.29.1

**Comment by brita-sed** [comment]
Retested with org.eclipse.sed.ifl.feature_1.2.29.1.jar. 

**Result:** The function has been implemented, and clicking on the option we navigate to the give element.
