### ISSUE TITLE
Slider should inactive in case of disabling filter scores

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#3]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 
1. Turn of filtering in the checkbox of filter scores.  
1. Set the filter value with the slider. 

**Expected results**
* When filtering scoring is turned off, the slider should be disabled/inactive. 

**Received results**
* Slider was active, in case of setting different values nothing happens. It's a little misleading.
![slider_active](https://user-images.githubusercontent.com/16755484/53966256-1bd9cd00-40f3-11e9-9e4e-30a5cb367c5e.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by brita-sed** [comment]
Bug is corrected in ifl_V0.3.

**Comment by brita-sed** [comment]
Bug appears again in ifl_V0.3_with_Time-8_9. Steps: 
1. Click iFL button. 
1. Load scores, for example sampleFor_joda-time.csv. 
1. Remove the tick from *filter scores* checkbox.
1. Load scores again. 

![load_scores_2x](https://user-images.githubusercontent.com/16755484/54842221-a6b0ef00-4cd1-11e9-9e63-77467e434950.PNG)

**Comment by brita-sed** [comment]
Retested on ifl_V0.4. 
Result: the bug remained in the program. 

![filter_score_again](https://user-images.githubusercontent.com/16755484/55082791-9e2a3100-50a2-11e9-8032-758012c29409.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.3.1

**Comment by brita-sed** [comment]
Still has bugs. 

**Steps:**
* Start Eclipse. 
* Import simple-junit project. 
* Click on iFL button. 
* Load scores...
* Filtering works fine. 
* Turn off Filter scores <=
* Load scores... again. 

**Expected result:**
* Filter scores <= was turned off, but the slider can be used. 

**Actual result:**
* Unexpected error during logging. 
* Log file and the video: z:\team\columbus\exchange\brita\iFL\filter_score_secontime\

**Version:**
* Eclipse: 2019-06 (4.12.0)
* iFL: org.eclipse.sed.ifl.feature_1.2.29.1.jar (version 1.2.3.1)

**Comment by Dhorvath1294** [comment]
I uploaded the wrong repository file which did not contain the changes on this issue. The repository file has been re-uploaded here: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.3.1
Sorry for the inconveniences.

**Comment by brita-sed** [comment]
Retested on version 1.2.3.1, works fine.
