### ISSUE TITLE
Setting every element to 0, then use filter score slider: message dialog appears plenty times

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#34]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load score...* button. 
1. Load the appropriate CSV file. 
1. Set all elements to not suspicios. 
1. When no element remained, set filter scores slider to different values. 

**Expected results**
* I got "There is no source code items to display.." error once. 

**Received results**
* I got "There is no source code items to display.." error, which is good, but after press OK button and set the slider again, every time I get his message, which is disturbing a little bit. Attached video: 
https://drive.google.com/open?id=1HI6pIoT7Xsk71veWY4i_iuAA9G70ZH_a

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
I think you attached the wrong video...

**Comment by brita-sed** [comment]
Sorry, I corrected it.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.34.1

**Comment by brita-sed** [comment]
Retested on V1.5.34.1. Result: *Correct*. There is no popup window now, only a message in the place of the table. 

![no_suspicious](https://user-images.githubusercontent.com/16755484/61867331-3dd3c080-aed7-11e9-8f35-311629713736.JPG)
