### ISSUE TITLE
Undefined elements after setting their score to 0, won't have any icon

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#35]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load score...* button. 
1. Load a modified CSV file, which doesn't contain all lines of the original CSV file. 
1. Set an undefined element to "Not suspicious". 

**Expected results**
* A green arrow should appear in the start of the line. (?) I'm not sure it's the expected result, but from undefined to zero also a decreasing operation. 

**Received results**
* Undefined elements after setting their score to 0, won't have any icon. 
* Scored elements after setting their score to 0 will have a green arrow. 
 
![set_undefined_to_zero](https://user-images.githubusercontent.com/16755484/55184702-1f60f100-5193-11e9-9234-aa18175d7124.jpg)

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
As of version 2.0, this issue seems to have been resolved.

![image](https://user-images.githubusercontent.com/48832842/73458119-0f96d800-4375-11ea-92e8-79994fbd5675.png)

![image](https://user-images.githubusercontent.com/48832842/73458168-263d2f00-4375-11ea-80b1-e030b66368be.png)

**Comment by geryxyz** [comment]
Yes. The icons know shows the last action on the elements. There should not
be any if there are not any action yet.
