### ISSUE TITLE
"Comparison method violates its general contract!" error message

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#38]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Modify the sampleFor_TestProject.csv: change method names to some special character, like  chinese or russian characters like this: 
name;score;interactive;details
由于对文件目录结构进行了大幅度修改;0.0915354789629943;yes;https://www.google.hu/search?q=DiffOddEven.<init>()V
"这门课程是刚上新的";0.6794483727594591;yes;"https://www.google.hu/search?q=Palindrome.main([Ljava/lang/String;)V"
Приобрёл всемирную известность;0.09853038713830786;yes;https://www.google.hu/search?q=Palindrome.isPalindromeLL()V
определённых кругах петербургского;0.36430160826641034;yes;https://www.google.hu/search?q=DiffOddEven.Node.<init>(I)V
1. Click *Load score...* button. 
1. Load the modified CSV file. 

**Expected results**
* I got user friendly message. (?)

**Received results**
* "Comparison method violates its general contract!" error message appears. Is this a right message? 
![chinese_russian_characters](https://user-images.githubusercontent.com/16755484/55235459-e590f880-522d-11e9-9ee8-15689a9ec5a8.JPG)
 

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Related issue**: #15

**Comment by Dhorvath1294** [comment]
I think this issue was caused by the sorting logic being unable to compare undefined scores to defined ones. It should be corrected in version: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**: there wasn't any error message like this.
