### ISSUE TITLE
Unhandled event loop exception in log when the user try to open wrong "details"

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#39]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Modify the sampleFor_TestProject.csv: change the first line like this (change website): 
DiffOddEven.<init>()V;0.0915354789629943;yes;"<iframe width='560' height='315' src='https://www.youtube.com/embed/LXIWRan3XGY' frameborder='0' allow='accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>"
1. Click *Load score...* button. 
1. Load the modified CSV file. 
1. Select this DiffOddEven method, then right click / Open details... 

**Expected results**
* The user will get a user friendly message that the given link cannot be opened. 

**Received results**
* Nothing happened. 
* Unhandled event loop exception in eclipse log: 
[unhandled_event_exception.txt](https://github.com/sed-szeged/iFL4Eclipse/files/3023373/unhandled_event_exception.txt)

 **Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.39.1

**Comment by brita-sed** [comment]
Retested on V1.5.39.1. Result: **Corrected**. 

![link_error_corrected](https://user-images.githubusercontent.com/16755484/61372597-e9599100-a897-11e9-95f0-b2b426e0ed7b.JPG)
