### ISSUE TITLE
Icon plans for local menu

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#4]
User can choose from different options while managing elements, icons would make the usage more transparent and comfortable: 
* This is faulty (terminal choice) ![faulty_16x16_complex](https://user-images.githubusercontent.com/16755484/53974471-ed63ee00-4102-11e9-848b-f96f07458558.png) ![faulty_32x32_complex](https://user-images.githubusercontent.com/16755484/53974478-efc64800-4102-11e9-9ae2-819b41d35516.png)
* Neither this, nor its context are faulty ![neither_faulty_16x16_complex](https://user-images.githubusercontent.com/16755484/53974425-d8875a80-4102-11e9-8b67-54a51dd37444.png) ![neither_faulty_32x32_complex](https://user-images.githubusercontent.com/16755484/53974431-dae9b480-4102-11e9-9865-55019a271ac4.png)
* This is not faulty ![not_faulty_16x16_complex](https://user-images.githubusercontent.com/16755484/53974348-ac6bd980-4102-11e9-9d45-257bc0f75715.png) ![not_faulty_32x32_complex](https://user-images.githubusercontent.com/16755484/53974353-aece3380-4102-11e9-80c2-cb28b31262f0.png)
* Navigate to selected ![navigate_selected_16x16](https://user-images.githubusercontent.com/16755484/53974552-17b5ab80-4103-11e9-9fb9-df02891a8e94.png) ![navigate_selected_32x32](https://user-images.githubusercontent.com/16755484/53974554-17b5ab80-4103-11e9-82a5-10bda0926e8d.png)
* Navigate to context ![navigate_context_16x16](https://user-images.githubusercontent.com/16755484/53974528-0a98bc80-4103-11e9-9a43-3c0f96486a34.png) ![navigate_context_32x32](https://user-images.githubusercontent.com/16755484/53974529-0a98bc80-4103-11e9-8745-b38313023eb0.png)
* User feedback is disabled ![feedback_disabled_16x16](https://user-images.githubusercontent.com/16755484/53976182-cdcec480-4106-11e9-8621-7ef01a1f52b3.png) ![feedback_disabled_32x32](https://user-images.githubusercontent.com/16755484/53976187-cf988800-4106-11e9-8613-352b9ab86c48.png)

Visualisation: 
![icon_plans_local_menu_small](https://user-images.githubusercontent.com/16755484/53974641-49c70d80-4103-11e9-9880-0c469514ca70.jpg)

![user_feedback_disabled](https://user-images.githubusercontent.com/16755484/53976198-d58e6900-4106-11e9-85be-f1fa1da1ec71.jpg)

The uploaded icons are in PNG format, with two sizes: 16x16 and 32x32

**Comment by brita-sed** [comment]
Note:
* (user feedback is disabled) should start with uppercase: (User feedback is disabled)
* The line above (user feedback..) is unnecessary

**Comment by geryxyz** [comment]
I really like these icons. However, the entries in the list are source code items (currently methods), using bug icon for all cases (faulty - not faulty) may deliver the wrong message that there is a "bug" in each of these items.

**Comment by brita-sed** [comment]
New icon plans: 
* Neither this, nor its context are faulty ![neither_faulty_source_16x16](https://user-images.githubusercontent.com/16755484/54029862-31f69480-41aa-11e9-9c8f-4d35616142ae.png) ![neither_faulty_source_32x32](https://user-images.githubusercontent.com/16755484/54029867-3458ee80-41aa-11e9-8e65-d22e42332491.png)
* This is not faulty ![not_faulty_source_16x16](https://user-images.githubusercontent.com/16755484/54029890-433fa100-41aa-11e9-9d3a-5b93b29f1edd.png) ![not_faulty_source_32x32](https://user-images.githubusercontent.com/16755484/54029895-45096480-41aa-11e9-9dfe-a1df8641a499.png)
* Navigate to selected ![navigate_to_selected_16x16](https://user-images.githubusercontent.com/16755484/54029908-52beea00-41aa-11e9-99f2-b0ef15b44a47.png) ![navigate_to_selected_32x32](https://user-images.githubusercontent.com/16755484/54029920-5b172500-41aa-11e9-9092-29d3e02b203b.png)
* Navigate to context ![navigate_to_context_16x16](https://user-images.githubusercontent.com/16755484/54029930-61a59c80-41aa-11e9-81dc-8bafb23c7dc1.png) ![navigate_to_context_32x32](https://user-images.githubusercontent.com/16755484/54029932-6407f680-41aa-11e9-8812-fa4e85bee887.png)

![icon_plans_local_menu_2](https://user-images.githubusercontent.com/16755484/54029998-94e82b80-41aa-11e9-9cdb-9af2ea9d87a6.jpg)

**Comment by brita-sed** [comment]
*Only User feedback disabled* icon is missing. Is it deliberate? Package: ifl_V0.3
![no_user_feedback](https://user-images.githubusercontent.com/16755484/54771569-db577480-4c05-11e9-95f3-694c8deef2d5.PNG)

**Comment by brita-sed** [comment]
New icons here: 
[round_3.zip](https://github.com/sed-szeged/iFL4Eclipse/files/3004240/round_3.zip)

Design plan: 
![new_local_menu](https://user-images.githubusercontent.com/16755484/54934737-4c0cd280-4f1f-11e9-8bcd-8e7b794b0309.jpg)

**Comment by brita-sed** [comment]
Corrections: 
![new_local_menu_2](https://user-images.githubusercontent.com/16755484/54940178-80d25700-4f2a-11e9-8757-ca505c56e706.jpg)

[round_3_jav.zip](https://github.com/sed-szeged/iFL4Eclipse/files/3004640/round_3_jav.zip)

**Comment by brita-sed** [comment]
New arrow icons: 
![uparrow_01](https://user-images.githubusercontent.com/16755484 54988637-2af7c080-4fb7-11e9-8083-c08e2a54700a.png) ![downarrow_01](https://user-images.githubusercontent.com/16755484/54988638-2af7c080-4fb7-11e9-825e-d511eebbff48.png)
![uparrow_02](https://user-images.githubusercontent.com/16755484 54988640-2af7c080-4fb7-11e9-840b-ac441e1c283e.png) ![downarrow_02](https://user-images.githubusercontent.com/16755484/54988641-2af7c080-4fb7-11e9-8c0d-365e05ece396.png)

**Comment by brita-sed** [comment]
New menu icon: 
![stay_stay_down](https://user-images.githubusercontent.com/16755484/55001249-7c627880-4fd4-11e9-9059-c450a3b19c0c.png)

**Comment by brita-sed** [comment]
Retested on ifl_V0.4
Result: corrected.
