### ISSUE TITLE
Sorting is not working properly at Name column

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#40]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load score...* button. 
1. Load the originally generated CSV file for the project. 
1. Sort by Name. 

**Expected results**
* Colums will sort properly. 

**Received results**
* Words starting with uppercase will be at the beginning of the list, the program shouldn't make difference between uppercase and lowercase in case of sorting. 
* Currenty the problem occcurs only with the Name column, because Signature and Parent type contains expressions with uppercase only. 
 
![sorting_name](https://user-images.githubusercontent.com/16755484/55247634-7674cd80-5248-11e9-97ba-15c794b162e6.jpg)

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by geryxyz** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.40.1

**Comment by brita-sed** [comment]
Retested on V1.5.40.1. Result: **Corrected**. 

![sorting_corrected](https://user-images.githubusercontent.com/16755484/61365277-bd361400-a887-11e9-97a5-e4e026b5a1d5.JPG)
