### ISSUE TITLE
NullpointerException in log, project: spring-boot-configuration-processor-test

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#41]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Download a bigger project, e.g.: https://github.com/spring-projects/spring-boot
1. Open it to the workspace (File / Open projects from File System).
1. Select a maven project (spring-boot-configuration-processor-test). 
1. Click iFL button on the toolbar. 

**Expected results**
* The iFL tab loads. 

**Received results**
* Although iFL tab loads, but there was error in eclipse log: 
*!MESSAGE Command 'org.eclipse.sed.ifl.commands.startCommand' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.eclipse.sed.ifl.commands.startCommand': java.lang.NullPointerException*

![spring_boot_nullpointer](https://user-images.githubusercontent.com/16755484/55317750-71df2d80-5471-11e9-8d65-48f88b040ae0.jpg)
[nullpointer_01.txt](https://github.com/sed-szeged/iFL4Eclipse/files/3028606/nullpointer_01.txt)

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by brita-sed** [comment]
If I press iFL button on "spring-bool-tools", I got "Non-Java project are selected" message and the same error in log.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.41.1

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.41.2

**Comment by brita-sed** [comment]
Retested on V1.5.41.2 Result: **Correct**.
