### ISSUE TITLE
"For input string.." error message in case of modified CSV

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#42]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\experiment\eclipse\ directory.

**Steps**
1. Choose a project (e.g. TestProject). 
1. Click iFL button on the toolbar. 
1. Load scores... and choose a modified CSV. I changed the first two line: 
"DiffOddEven.<init>()V;邮政金华市包裹业务局;yes;https://www.google.hu/search?q=DiffOddEven.<init>()V
"Palindrome.main([Ljava/lang/String;)V";邮政金华市包裹业务局;yes;"https://www.google.hu/search?q=Palindrome.main([Ljava/lang/String;)V""

**Expected results**
* User friendly message about that the given score values should be a number between 0 and 1. 

**Received results**
* For input string: ... error message. 
* No error in log. 
![for_input_string_xxx](https://user-images.githubusercontent.com/16755484/55333129-f1cbbe80-5496-11e9-93bc-717a2a1fe87c.JPG)

**Environment:**
* Package: z:\team\columbus\projects\kutatas\iFL\ifl_V0.4\
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.42.1

**Comment by brita-sed** [comment]
Retested on V1.5.42.1. Result: Corrected. 

![corrected_hibauzenet](https://user-images.githubusercontent.com/16755484/61316518-73a2e600-a801-11e9-8b93-3ab506fb6f18.JPG)
