### ISSUE TITLE
Design plan/recommendation: filtering by name

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#43]
If there is a lot of element, it may be necessary to filter items by name or parent type. It would be enough to have a single text input field with which the user could filter items based on text values.

Design plan: 
![filter_by_name](https://user-images.githubusercontent.com/16755484/55340487-1af34b80-54a5-11e9-8e67-e4c0042bb263.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.43.1

**Comment by brita-sed** [comment]
Filtering by name is working, it's great! But the layout can be approved: there is a big empty space currently in the right side of the workspace, so the field of name-filtering can be placed next to filter context size. @geryxyz , oppinion? 

![filter_by_name](https://user-images.githubusercontent.com/16755484/73006172-7e6eb100-3e0a-11ea-9476-101fbe729232.jpg)

**Comment by geryxyz** [comment]
@brita-sed you are right about that, but we prefer to handle these things separately. Please report a new issue for this and every following UI related questions. So we are able to close this one.
