### ISSUE TITLE
Icon plans for the main table

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#45]
The following icons have been made: 

- Score: ![icons_for_table_iFL_score_16x16](https://user-images.githubusercontent.com/16755484/57710075-80258980-766c-11e9-9cad-00ad9c81b121.png) ![icons_for_table_iFL_score_32x32](https://user-images.githubusercontent.com/16755484/57710076-80be2000-766c-11e9-848d-4594da5d6ee7.png)
- Name: ![icons_for_table_iFL_name_16x16](https://user-images.githubusercontent.com/16755484/57712307-a1887480-7670-11e9-9aa9-dc933c532853.png) ![icons_for_table_iFL_name_32x32](https://user-images.githubusercontent.com/16755484/57712308-a1887480-7670-11e9-9dd3-fe8c7c42d6c5.png)
- Signature: ![icons_for_table_iFL_signature_16x16](https://user-images.githubusercontent.com/16755484/57712323-aa794600-7670-11e9-8dae-a5e079dd48d1.png) ![icons_for_table_iFL_signature_32x32](https://user-images.githubusercontent.com/16755484/57712325-aa794600-7670-11e9-95c6-1309d2bc1130.png)
- Parent type: ![icons_for_table_iFL_parents_16x16](https://user-images.githubusercontent.com/16755484/57710010-608e6100-766c-11e9-8a68-a703d78df7c1.png) ![icons_for_table_iFL_parents_32x32](https://user-images.githubusercontent.com/16755484/57710011-6126f780-766c-11e9-8bbc-72248ef2f41b.png)
- Path: ![icons_for_table_iFL_path_02_16x16](https://user-images.githubusercontent.com/16755484/57710058-76038b00-766c-11e9-9c90-6d320dded457.png) ![icons_for_table_iFL_path_02_32x32](https://user-images.githubusercontent.com/16755484/57710059-76038b00-766c-11e9-8e3c-a34ba6353152.png)
- Positon: ![icons_for_table_iFL_position_16x16](https://user-images.githubusercontent.com/16755484/57710039-700daa00-766c-11e9-9ebc-db97b771063d.png) ![icons_for_table_iFL_position_32x32](https://user-images.githubusercontent.com/16755484/57710040-700daa00-766c-11e9-8f79-8b810b480eef.png)
- Context size: ![icons_for_table_iFL_contexsize_16x16](https://user-images.githubusercontent.com/16755484/57710023-697f3280-766c-11e9-8a2a-1e4ceff4add5.png) ![icons_for_table_iFL_contexsize_32x32](https://user-images.githubusercontent.com/16755484/57710024-6a17c900-766c-11e9-9892-c1af4fc0c581.png)

Design plan: 
![kepernyoterv_tablazat](https://user-images.githubusercontent.com/16755484/57712383-c2e96080-7670-11e9-8205-0b48b0c0173b.jpg)

**Comment by Dhorvath1294** [comment]
The table has been replaced by a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
