### ISSUE TITLE
Create a history view to replace score change icons

### ISSUE THREAD

**Issue by geryxyz** [sed-szeged/iFL4Eclipse#47]
The goal is to provide a way to the user to inspect previous actions on source code items. The user has to select any source code item (e.g. method) in the iFL view, and if there are any previous feedback related to it, they will display as a history bar. The table also shows the last feedback related to each item in the first column ("Last action").

**Comment by geryxyz** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.47.1

**Comment by brita-sed** [comment]
Retested on V1.2.47.1. Result: **works properly**. 

![history](https://user-images.githubusercontent.com/16755484/61360353-93c4ba80-a87e-11e9-8839-9ec7783c1e3e.JPG)
