### ISSUE TITLE
Load scores, Hide undefined and warning dialog icons

### ISSUE THREAD

**Issue by Dhorvath1294** [sed-szeged/iFL4Eclipse#48]
Addition of new icons and a custom warning dialog.

**Comment by Dhorvath1294** [comment]
#31 #10

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.48.1

**Comment by brita-sed** [comment]
As all the related issues have been closed, this issue can be closed too.
