### ISSUE TITLE
Because of rounding inaccuracy in case of giving manually the biggest filter score causes Input format error

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#50]
**Steps:**
* Start Eclipse. 
* Import simple-junit project. 
* Click on iFL button. 
* Load scores...
* Give filter score manually, in this case the maximum value is 0.779
* Click Apply button. 

**Expected result:**
* The maximum value is acceptable. 

**Actual result:**
* Due to the rounding error, the system does not accept 0.779, only 0.778.
![greater_value](https://user-images.githubusercontent.com/16755484/60340398-c11ef680-99ab-11e9-9cf8-6c6cb93a7d55.jpg)

**Version:**
* Eclipse: 2019-06 (4.12.0)
* iFL: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.2.48.1

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.50.1

**Comment by brita-sed** [comment]
**Retested** on V2.0.50.1. Result: **Corrected**.
