### ISSUE TITLE
Setting all element to not suspicious, min-max values are 0,000, but the slider contains original values

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#51]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key file is in the C:\....\eclipse\ directory.

**Steps**
1. Select a project (TestProject). 
1. Click iFL button on the toolbar. 
1. Click *Load score...* button. 
1. Load the appropriate CSV file. 
1. Set all elements to not suspicios. 
1. When no element remained, set filter scores slider to different values. 

**Expected results**
* "There are no source code items..." message appears in the place of the table, and all scores are 0,000 on the slider (as the minimum and maximum values are 0,000). 

**Received results**
* The original values appears on the slider. 

![no_suspicious_numberonslider](https://user-images.githubusercontent.com/16755484/61867639-f13cb500-aed7-11e9-831b-89075fcd1b7b.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.34.1
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version:  2019-06 (4.12.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.0.51.1

**Comment by brita-sed** [comment]
As I cannot set every element to not suspicious (User feedback disabled items), the bug isn't valid anymore. Issue can be closed.

**Comment by brita-sed** [comment]
The bug appears again, User feedback disabled items can set to non-suspicious with context operations. 

![no_to_display](https://user-images.githubusercontent.com/16755484/76608309-b2667880-6515-11ea-934e-8f452f73793d.jpg)

**Comment by brita-sed** [comment]
There is no "not suspicios" operation anymore. Retested on version: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs.3
