### ISSUE TITLE
Leave port number emtpy, Cancel, then give valid data -> iFL error (For input string) and NullPointerException

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#59]
**Precondition**
* GremlinServer is running. 
* Eclipse has been launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Set host name, but leave the port number field empty. 
1. Click OK button. 
1. In "Enter user ID" window click Cancel button. 
1. Give host name again (localhost), and a Port number too (8182). 
1. Click OK button. 
1. Give a User ID (e.g. brita). 
1. Click OK button. 

**Expected results**
* As we give valid data, the plugin should works. 

**Received results**
* First we get "For input string: "" " error during iFL initialization because of the empty port number. 
* Then "java.lang.NullPointerException". 

[debug.log](https://github.com/sed-szeged/iFL4Eclipse/files/4324920/debug.log)
![nullpointer](https://user-images.githubusercontent.com/16755484/76536365-8ea32400-647c-11ea-8e5f-34ff541e04a3.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

The input dialogs no longer exist. The input fields have been moved to the iFL Preference Page.

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
