### ISSUE TITLE
Filter scores to maximum (and minimum): different values at the slider left and right side

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#6]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 
1. Click *Load scores...* button. 
1. Load C:\experiment\eclipse\sampleFor_DemoProject.csv. 
1. Filter scores moving the slider to the maximum. 

**Expected results**
* Filter score <= [value] and the value at the end should be the same. 

**Received results**
* It tried to maximize the filtered score twice and in both case I get diffferent values. For example: 
** Filter score <= 0.8120 and 0.8228 at the end of the slider. 
** Filter score <= 0.7660 and 0.7762 at the end of the slider. 

![filter_scores_wreid_01](https://user-images.githubusercontent.com/16755484/54036387-cf0df900-41bb-11e9-8b69-54be29cf9dca.jpg)
![filter_scores_wreid_02](https://user-images.githubusercontent.com/16755484/54036386-cf0df900-41bb-11e9-9a97-5cba3b4ce05f.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by brita-sed** [comment]
The same is true for the minimum score value. 

![slider_minimum](https://user-images.githubusercontent.com/16755484/54038592-2e223c80-41c1-11e9-8b84-ec59218c06cf.jpg)

**Comment by brita-sed** [comment]
Still have problems in ifl_V0.3: 
![filter_score_max](https://user-images.githubusercontent.com/16755484/54770337-4c495d00-4c03-11e9-8bce-f85d3dc4c1ce.jpg)
![filter_score_min](https://user-images.githubusercontent.com/16755484/54770339-4c495d00-4c03-11e9-8980-cf637e2ea17d.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.6.1

**Comment by brita-sed** [comment]
Retested on V1.5.6.1. Result: **Corrected.**
