### ISSUE TITLE
Non-existing host: error message should be English, NullPointerException in log

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#60]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Set a non-existing host name and a port.  
1. Click OK button. 
1. Give an user ID. 
1. Click OK button. 

**Expected results**
* The user will get a user-friendly message in English. 

**Received results**
* As my OP system's language is Hungarian, I got Hungarian error message. 
* org.eclipse.core.commands.ExecutionException: Error executing 'org.eclipse.sed.ifl.commands.startCommand': java.lang.NullPointerException in log. 

![nincs_ilyen_allomas](https://user-images.githubusercontent.com/16755484/76540511-85b55100-6482-11ea-91bf-a8cef3e7a99b.jpg)
[log_nincs_ilyen_allomas.txt](https://github.com/sed-szeged/iFL4Eclipse/files/4325159/log_nincs_ilyen_allomas.txt)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
When we click iFL button again, the following message occurs (without "Nincs ilyen állomás" text): 

![image](https://user-images.githubusercontent.com/16755484/76542811-d67a7900-6485-11ea-93d8-0073ee7e1dfd.png)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

The input dialogs no longer exist. Input fields have been moved to the iFL Preference Page.
