### ISSUE TITLE
Shaking and vibrating columns

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#63]
When I make operations with iFL table, columns are usually shaking and vibrating. I made a video from this, but in real life the result are more spectacular. 

Video can be found here: z:\team\columbus\projects\kutatas\iFL\vibration.avi

**Package**: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0

**Comment by Dhorvath1294** [comment]
The table has been replaced by a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
