### ISSUE TITLE
Filter context size field is limited to 100, it should be bigger

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#65]
Filter context size field is limited to 100, but there could be bigger value, as the picture shown below. So if I'd like to find elements with 116 context size, I cannot filter them. The limit should be bigger. 

![context_filter_limitation](https://user-images.githubusercontent.com/16755484/76632218-25d2af00-6543-11ea-91bc-17897444dc24.jpg)

**Package**: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7

I've changed the limit to 1000.

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7. Result: **Corrected**.
