### ISSUE TITLE
In Terminal choice confirmation popup the extra line should be removed

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#66]
When the user select an element for set it the faulty one (Right click -> Selected items seem faulty (terminal choice)), in the popup window there will be a table with one extra line. This extra line with no function should be removed. 

![to_line](https://user-images.githubusercontent.com/16755484/76635575-fa05f800-6547-11ea-9c3c-a495d5ca6217.JPG)

**Package**: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs

That space is preserved for the horizontal scroll bar in SWT. I can only make it disappear by setting the style of the table to NO_SCROLL, but that would also disable the vertical scroll bar, which we need.

**Comment by brita-sed** [comment]
In this case this issue is **wont' fixed**. Can be closed.
