### ISSUE TITLE
Ordering by Last action column does not work

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#67]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. *Setting host name, port number and User ID*
1. Select a project. 
1. Click iFL button. 
1. Load appropriate scores. 
1. Make some actions on some element. 
1. Order the table by Last action column. 

**Expected results**
* The table will be ordered as the user set. 

**Received results**
* Nothing happens, the ordering won't happen. 

![ordeing_by_last_action](https://user-images.githubusercontent.com/16755484/76640524-65ec5e80-6550-11ea-8b02-daf3ab9d7471.jpg)

**Related issue:**
* #58 

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by brita-sed** [comment]
Looks like the problem still occurs in the new grid view as well. Retested on: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.4.52.3

![last_action_rendezes](https://user-images.githubusercontent.com/16755484/81699022-14d0ec00-9467-11ea-8ade-678866cd877f.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Related issue: #140

**Comment by brita-sed** [comment]
Retested on version V2.5.140.1. Result: **corrected** with the related issue.
