### ISSUE TITLE
At first load iFL tab is empty - need to resize window to see the content

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#68]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Setting a valid host name, port number and User ID. 
1. Click OK button. 

**Expected results**
* iFL tab appears with the appropriate buttons and table of element (without undefined score). 

**Received results**
* The tab was empty, the User needs to resize the window to see the content. 

![resize_tab](https://user-images.githubusercontent.com/16755484/76746865-797a0e00-6778-11ea-8721-b24abc6559a4.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The table has been replaced by a card-like UI.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**. There is no popup with login settings.
