### ISSUE TITLE
Design plans for filtering table by interactivity (User feedback enabled/disabled)

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#69]
Filtering by interactivity column would be useful. Input fields for filtering can be near to the Filter context size field. Plans: 

![disabled_enabled_filter_1](https://user-images.githubusercontent.com/16755484/76759517-1d20e980-678c-11ea-9043-b14ff73521fe.jpg)
![disabled_enabled_filter_2](https://user-images.githubusercontent.com/16755484/76759520-1e521680-678c-11ea-8385-0a074d647832.jpg)

**Comment by Dhorvath1294** [comment]
Sort by interactivity option has been added to sort options.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
