### ISSUE TITLE
There is no header text in "Enter host name and port number" popup

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#70]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Setting a valid host name, port number and User ID. 

**Expected results**
* Popup windows appear properly. 

**Received results**
* There is no header text in "Enter host name and port number" popup. 

![no_header](https://user-images.githubusercontent.com/16755484/76764934-f8317400-6795-11ea-9771-f156c503ae22.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

This dialog window no longer exists; the input fields have been moved to the iFL Preference Page.

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
