### ISSUE TITLE
After an element operation has been performed, the Filters scores turned on

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#73]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Setting a valid host name, port number and User ID. 
1. Load scores. 
1. Turn off filter scores. 
1. Select a line, then right click on it. 
1. Make an operation (e.g. Selected items seems not suspicious). 

**Expected results**
* The operation is performed correctly, and only that operation is performed, which was selected. 

**Received results**
* After Selected items seems not suspicious operation has been performed, the Filters scores turned on. 
![operation_filter_scores](https://user-images.githubusercontent.com/16755484/76781570-38e9b700-67af-11ea-97b2-7ae370dfe488.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
The filter has been completely reworked.
