### ISSUE TITLE
iFL preferences, Restore Defaults: User ID, Host and Port cannot be changed

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#74]
In Window / Preferences, if the user clicks Restore Defaults button, User ID, Host and Port will be empty, and cannot be modified. According to the latest information, "I think it would be good if we couldn't put them there, and user cannot modify it, but Gergo should told". 

![restore_defaults_inactive](https://user-images.githubusercontent.com/16755484/76963995-3b205280-6922-11ea-8dd2-4c291591e609.jpg)

**Comment by geryxyz** [comment]
I think we already discussed it with @Dhorvath1294 so it will be changed soon.

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
