### ISSUE TITLE
Run graph = Neo4jGraph.open(...) command second time causes error in gremlin consol log

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#77]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Setting a valid host name, port number and User ID. 
1. Load scores. 
1. Run the following commands in gremlin console: 
* `graph = Neo4jGraph.open('/mnt/c/work/iFL/server/apache-tinkerpop-gremlin-server-3.4.0/ifl/')`
* `g = graph.traversal()`
* `g.V().hasLabel("id")`
* `graph = Neo4jGraph.open('/mnt/c/work/iFL/server/apache-tinkerpop-gremlin-server-3.4.0/ifl/')`

**Expected results**
* On the second run of `graph = Neo4jGraph.open('/mnt/c/work/iFL/server/apache-tinkerpop-gremlin-server-3.4.0/ifl/')` command, a user-friendly error will occur. 

**Received results**
* Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /mnt/c/work/iFL/server/apache-tinkerpop-gremlin-server-3.4.0/ifl
Type ':help' or ':h' for help.
Display stack trace? [yN]y

[error_starting.log](https://github.com/sed-szeged/iFL4Eclipse/files/4349654/error_starting.log)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by geryxyz** [comment]
This is the expected behavior. You can not open the same graph twice. Anyway gremlin consol is not part of the iFL so we won't address any errors related to it.
