### ISSUE TITLE
Multiple selection on items: Navigate to selected, Navigate to context and Open details... shouldn't be active

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#78]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Setting a valid host name, port number and User ID. 
1. Load scores. 
1. Select multiple items. 
1. Right click. 

**Expected results**
* Only the first 5 operation is active, the other three fuction cannot be interpreted for multiple items. 

**Received results**
* Every function was active, Navigate to selected, Navigate to context and Open details... shouldn't be active. 

![multiple_selection_inactive](https://user-images.githubusercontent.com/16755484/77052642-69a73780-69cd-11ea-8ad1-87ea179506eb.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by geryxyz** [comment]
It should and will be interpreted.
