### ISSUE TITLE
Giving wrong Directory preference, then give a new text preference: error message disappears

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#79]
**Precondition**
* GremlinServer is running. 
* C:/experiment/eclipse/eclipse.exe has launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 
* Logging is set. 

**Steps**
1. Window / Preferences. 
1. Choose iFL Preferences submenu. 
1. Set a wrong Directory preference. 
1. Set a new text preference. 

**Expected results**
* "Value must be an existing directory" message won't appear until the user correct it. 

**Received results**
* After the user give a new text preference, the error message disappears. 
* Video: z:\team\columbus\projects\kutatas\iFL\ifl_pref.avi

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

Directory preference can no longer be found on the iFL Preference Page.

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
