### ISSUE TITLE
Choosing second time "This is not faulty" to the same element: green triangle disappears

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#8]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 
1. Click *Load scores...* button. 
1. Load C:\experiment\eclipse\sampleFor_DemoProject.csv. 
1. Select some editable line from the table. 
1. Choose "This is not faulty" option from the right-click menu. 
1. Choose the same element as in Step 5, set "This is not faulty".

**Expected results**
* Nothing happens, because the operation is done first, at second time the operation is unneccessary.  

**Received results**
* The green triangle disappears. 
![triangle_disappears](https://user-images.githubusercontent.com/16755484/54042707-13ed5c00-41cb-11e9-8865-1d37c5c99bcd.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by brita-sed** [comment]
Same behaviour in case of "Neither this, nor its context are faulty".

**Comment by geryxyz** [comment]
This is part of a bigger problem. The original idea with these icons was to show the changes in score values after feedback. Since there is no change after giving the same feedback there are no icons either.

That said, we have to rethink this feature to be more user-friendly and straight forward.

**Comment by Dhorvath1294** [comment]
The score history and the table have been completely reworked or - in case of the table itself - replaced.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
