### ISSUE TITLE
Missing header text in Custom feedback popup window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#82]
**Precondition**
* .../eclipse.exe has been launched.  
* Key and scenario files are in the C:\....\eclipse\ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Select an item, then right click. 
1. Click Custom feedback... 

**Expected results**
* Every element of the table is accurate and in place. 

**Received results**
* The header of the window is missing. It should be "Custom feedback..."

![missing_header](https://user-images.githubusercontent.com/16755484/77528173-bf785580-6e8d-11ea-8744-06ae955c5063.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
