### ISSUE TITLE
 List of methods in tables has some inaccuracy in layout

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#84]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Select an item, then right click. 
1. Click Custom feedback... button. 

**Expected results**
* List of methods are easy to view, transparent and user friendly.

**Received results**
* List of methods in tables are not user friendly: 
** There are two column is the first table
** Second table is too small

![table_layouts](https://user-images.githubusercontent.com/16755484/77551906-2b20e980-6eb3-11ea-8f0d-25845a9fd74e.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/LogTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.

![corrected_table](https://user-images.githubusercontent.com/16755484/79997758-2fdcbb80-84ba-11ea-9170-df29e6511c9d.JPG)
