### ISSUE TITLE
In Custom feedback... window, there can be a method selected which doesn't have related dot. 

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#86]
In Custom feedback... window, there can be a method selected which doesn't have related dot. 

![no_selection](https://user-images.githubusercontent.com/16755484/77661184-971a5500-6f7a-11ea-88c2-7c37593022be.jpg)

"If I think correctly, only those methods have a dot which have defined scores.  The list is sorted by name and does not look at the score."

**Comment by Dhorvath1294** [comment]
Currently, this feature works like this: the number of dots are limited. If there are too many code elements, displaying all of them causes serious performance issues (i. e. slow loading). So in this case, only a fraction of randomly chosen code elements are represented by dots to give a visual clue to the user about the changes to score.

https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.5

**Comment by brita-sed** [comment]
Retested on version V2.5. Result: **corrected**.
