### ISSUE TITLE
Custom feedback... window is not resizable, longer method names slip off from the UI

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#87]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a bigger project (joda-time). 
1. Click iFL button. 
1. Load scores. 
1. Select an item, then right click. 
1. Click Custom feedback... button. 

**Expected results**
* The window is resizable. 
* Even the project has a lot of (and long-named) method, the user can see every part of the window. 

**Received results**
* Window is not resizable. 
* As the project has a lot of method, and some with long name, end of the 3rd part slips out from the UI. 

![no_scroll](https://user-images.githubusercontent.com/16755484/77665053-61c43600-6f7f-11ea-9b71-bb033343ff60.jpg)

![longer_method_names](https://user-images.githubusercontent.com/16755484/77665277-bc5d9200-6f7f-11ea-94c6-e79b1299e4f2.jpg)

![long_names](https://user-images.githubusercontent.com/16755484/77670396-722bdf00-6f86-11ea-94f0-0812f899e7a1.JPG)

![custom_feedback_layout](https://user-images.githubusercontent.com/16755484/77758585-84b02200-7033-11ea-8041-4c4257e7a197.JPG)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-feedback-dialog-bugs

**Comment by brita-sed** [comment]
Retested, corrected. Names of the methods are readable, columns of tables are resizeable. 

![slip_off_name_corrected](https://user-images.githubusercontent.com/16755484/92578104-b89e9d00-f28b-11ea-9c2f-f91767c2fcfa.jpg)
