### ISSUE TITLE
Improvement of the slider

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#88]
If we make actions on elements and scores are changing, apparently the slider subdivisions are also changing visually.

![slider_sizes](https://user-images.githubusercontent.com/16755484/77674452-e87f1000-6f8b-11ea-9af8-8ad0416bbb55.jpg)

"The smallest value of a slider is the lowest score in the list (without a filter), the highest is the highest, and as I remember correctly the grade is fixed, so not the grade changes but the slider below."

To make the slider look more user friendly, I make some recommendations with a rank five slider: 

![slider_design_01](https://user-images.githubusercontent.com/16755484/77675832-be2e5200-6f8d-11ea-871b-12646c724526.jpg)

**Comment by Dhorvath1294** [comment]
The slider is no longer being used.
