### ISSUE TITLE
User feedback disabled, local menu - small bugs

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#9]
**Precondition**
* C:/experiment/eclipse/eclipse.exe has launched.  

**Steps**
1. Select a project (DemoProject). 
1. Click iFL button on the toolbar. 
1. Click *Load scores...* button. 
1. Load C:\experiment\eclipse\sampleFor_DemoProject.csv. 
1. Select some "user feedback disabled" line from the table.
1. Right click on this item. 

**Expected results**
* The menu appears in a correct style with the correct options. 

**Received results**
* (user feedback is disabled) should start with uppercase: (User feedback is disabled)
* The line above (user feedback..) is unnecessary
![user_feedback_disabled](https://user-images.githubusercontent.com/16755484/54113895-889de180-43e9-11e9-8606-ad46af60c59a.jpg)

**Environment:**
* Operating System: Windows 10 Pro, 64 bit (VM)
* Eclipse version: 2018-12 (4.10.0), Build id: 20181214-0600

**Comment by brita-sed** [comment]
The bug has corrected in ifl_V0.3. **Note**: *Navigate to selected* and other menus starts uppercase without a dot (it's not a sentence), so why *(User feedback is desabled.)* needs it? Brackets are also unnecessary in my oppinion.

**Comment by brita-sed** [comment]
Retested on ifl_V0.4
Result: dot is unnecessary
![dot_is_unnecessary](https://user-images.githubusercontent.com/16755484/55083770-55737780-50a4-11e9-9cfd-b3062b2abb16.jpg)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V1.5.9.1

**Comment by brita-sed** [comment]
Retested on V1.5.9.1. Result: **Corrected**. 

![dot_corrected](https://user-images.githubusercontent.com/16755484/61318780-21b08f00-a806-11e9-8a67-64485d15cd42.jpg)
