### ISSUE TITLE
Lot of elements is faulty: description disappers from terminal choice popup window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#90]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Select a lot of item, then right click. 
1. Click Selected items seems faulty (terminal choice). 

**Expected results**
* The size of the window is correct, scroll bar is available. 

**Received results**
* The description disappears, only table of elements are visible. 

![too_much_selected](https://user-images.githubusercontent.com/16755484/77753288-7d841680-7029-11ea-9d36-8ba262570bab.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs

The scroll bar on the side now appears as soon as there are 8 elements present.

**Comment by brita-sed** [comment]
Retested on version V2.fix-terminal-dialog-bugs. Result: **corrected**.

![description_corrected](https://user-images.githubusercontent.com/16755484/89656499-f5155c80-d8cb-11ea-815f-9ee5fccfe713.jpg)
