### ISSUE TITLE
Last action column should be resizable

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#92]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores. 
1. Resize Last action column. 

**Expected results**
* Last action column is resizable. 

**Received results**
* Last action column was not resizable. 

**Related issue:**
* #75

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.7
