### ISSUE TITLE
Corrections of "iFL session already active" dialog window

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#93]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Click iFL button again. 

**Expected results**
* Popup window is correct. 

**Received results**
* Cancel button is unnecessary, OK button is enough. 
* iFL session **IS** already active -> "is" is missing from the header

![ok_cancel](https://user-images.githubusercontent.com/16755484/77768188-6998de80-7042-11ea-9563-bcdf1ba17883.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

iFL session is already active

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.

![already_dialog_corrected](https://user-images.githubusercontent.com/16755484/79997353-c8267080-84b9-11ea-9238-6aa3a4005e40.JPG)
