### ISSUE TITLE
Unhandled event loop exception, java.lang.UnsupportedOperationException while giving feedback before loading scores

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#94]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Select an element from the table. 
1. Right click on an element -> Custom feedback...
1. Set some new value, then click OK. 

**Expected results**
* Custom feedback should be inactive before loading scores. 

**Received results**
* Unhandled event loop exception, java.lang.UnsupportedOperationException
* Log file: 
[UnsupportedOperationException_log.txt](https://github.com/sed-szeged/iFL4Eclipse/files/4394518/UnsupportedOperationException_log.txt)

**Related issue:**
* #91

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.1

Expected behavior: feedback is enabled and feedback can be given on undefined elements, but it makes no changes to the given score (score remains undefined, score history shows no changes).

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.1. Result: **Corrected**.
