### ISSUE TITLE
Unhandled event loop exception, java.lang.NullPointerException when ordering by Interactivity or Last action column

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#95]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Order the table by Last action and Interactivity column. 

**Expected results**
* Ordering will proceed correctly. 

**Received results**
* Unhandled event loop exception, java.lang.NullPointerException
* Log file: [NullPointerException_log.txt](https://github.com/sed-szeged/iFL4Eclipse/files/4394740/NullPointerException_log.txt)

**Related issue:**
* #58 #67

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV1.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6

**Comment by brita-sed** [comment]
Retested on https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.3.6. Result: **corrected**.
