### ISSUE TITLE
Terminal choice window: methods should be in alphabetial order, methods with the same name should have extra information

### ISSUE THREAD

**Issue by brita-sed** [sed-szeged/iFL4Eclipse#97]
**Precondition**
* GremlinServer is running. 
* .../eclipse.exe has launched.  
* Key files are in the .../eclipse/ directory.
* iFL plugin has been installed. 

**Steps**
1. Select a project. 
1. Click iFL button. 
1. Load scores...
1. Select some items. 
1. Right click > Selected items seems faulty (terminal choice). 

**Expected results**
* Methods should be in order. 
* If there are several methods with the same name, it would be worthwhile to distinguish them by providing additional information.

![main_lots](https://user-images.githubusercontent.com/16755484/78553865-52a87800-780a-11ea-8447-23f389ff11fb.jpg)

**Environment:**
* Package: https://github.com/sed-szeged/iFL4Eclipse/releases/tag/CustomFeedbackTestV2.0
* Operating System: Windows 10 Pro, 64 bit
* Eclipse version: 2019-09 R (4.13.0)

**Comment by Dhorvath1294** [comment]
https://github.com/sed-szeged/iFL4Eclipse/releases/tag/V2.fix-terminal-dialog-bugs

Methods are now appearing in alphabetical order. If there are two or more methods with the same name, that method's name needs to be typed in only once by the user.

**Comment by brita-sed** [comment]
The bug has been **corrected**. 

![sok_main_corrected](https://user-images.githubusercontent.com/16755484/91566685-53ba7d00-e944-11ea-93d4-68b27023d0d4.jpg)
